#author -Riyan Rickson




cric={
    #INDIA-----------------------------------------------------------------------------------------------------------------------------------------------------
    '11':("Sachin Tendulkar", "Virat Kohli", "Rohit Sharma", "MS Dhoni",
    "Sourav Ganguly", "Rahul Dravid", "VVS Laxman","Virender Sehwag", "Gautam Gambhir", "Shikhar Dhawan", "Ajinkya Rahane",
    "Cheteshwar Pujara", "KL Rahul","Sunil Gavaskar", "Mohammad Azharuddin", "Suresh Raina",
    "Dinesh Karthik", "Rishabh Pant", "Shreyas Iyer", "Suryakumar Yadav",
    "Prithvi Shaw", "Shubman Gill", "Ishan Kishan","hanuma vihari","wriddhiman saha","manish pandey"
    ,"Karun nair","muruli vijay","abhishek sharma","yashaswi jaiswal","tilak varma","druv jurel","rinku singh"),

    '21':(
    "Kapil Dev",
    "Ravindra Jadeja",
    "Hardik Pandya",
    "Irfan Pathan",
    "Yusuf Pathan",
    "Ravi Shastri",
    "Manoj Prabhakar",
    "Stuart Binny",
    "Shardul Thakur",
    "Axar Patel",
    "Washington Sundar",
    "Sanjay Bangar",
    "Mohinder Amarnath",
    "Lala Amarnath",
    "Vinoo Mankad",
    "Kedar Jadhav",
    "Suresh Raina",
    "Yuvraj Singh",
    "Harbhajan Singh",
    "Ramesh Powar",
    "Deepak Chahar",
    "Abhishek Sharma",
    "Vijay Shankar",
    "Shivam Dube",
    "Krunal Pandya"
    ),
    

     '31': (
    "Jasprit Bumrah",
    "Mohammed Shami",
    "Ishant Sharma",
    "Bhuvneshwar Kumar",
    "Harbhajan Singh",
    "Anil Kumble",
    "Ravichandran Ashwin",
    "Yuzvendra Chahal",
    "Kuldeep Yadav",
    "Deepak Chahar",
    "Shivam Mavi",
    "Shardul Thakur",
    "Mohammed Siraj",
    "Prasidh Krishna",
    "Varun Chakravarthy",
    "T. Natarajan",
    "Arshdeep Singh",
    "S. Sreesanth",
    "Zaheer Khan",
    "Piyush Chawla",
    "Sandeep Sharma",
    "Ravi Bishnoi",
    "Umran Malik"
    ),
    '41':(
    "Harmanpreet Kaur",
    "Smriti Mandhana",
    "Shefali Verma",
    "Jemimah Rodrigues",
    "Deepti Sharma",
    "Richa Ghosh",
    "Harleen Deol",
    "Yastika Bhatia",
    "S. Meghana",
    "Shikha Pandey",
    "Rajeshwari Gayakwad",
    "Pooja Vastrakar",
    "Renuka Singh Thakur",
    "Taniya Bhatia",
    "Radha Yadav",
    "Meghna Singh",
    "Anjali Sarvani",
    "Devika Vaidya",
    "Jintimani Kalita",
    "Saika Ishaque",
    "Shreyanka Patil",
    "Kanika Ahuja",
    "Amanjot Kaur",
    "Uma Chetry"
),
#AUSTRALIA-----------------------------------------------------------------------------------------------------------------------------------------------------

    '12':(
    "David Warner",
    "Steve Smith",
    "Usman Khawaja",
    "Marnus Labuschagne",
    "Travis Head",
    "Shaun Marsh",
    "Mitchell Marsh",
    "Cameron Bancroft",
    "Marcus Harris",
    "Joe Burns",
    "Peter Handscomb",
    "Matt Renshaw",
    "Aaron Finch",
    "George Bailey",
    "Shane Watson",
    "Michael Clarke",
    "Ricky Ponting",
    "Mike Hussey",
    "Alex Carey",
    "Tim Paine",
    "Phil Hughes",
    "Josh Inglis"
),

'22':(
    "Mitchell Marsh",
    "Glenn Maxwell",
    "Marcus Stoinis",
    "Cameron Green",
    "Ashton Agar",
    "James Faulkner",
    "Shane Watson",
    "Moises Henriques",
    "Dan Christian",
    "Hilton Cartwright",
    "Aaron Hardie",
    "Michael Neser",
    "Sean Abbott",
    "Ben Cutting",
    "Ellyse Perry",
    "Ashleigh Gardner",
    "Tahlia McGrath",
    "Jess Jonassen",
    "Sophie Molineux",
    "Grace Harris",
    "Annabel Sutherland"
    
),

'32':(
    "Mitchell Starc",
    "Pat Cummins",
    "Josh Hazlewood",
    "James Pattinson",
    "Peter Siddle",
    "Jackson Bird",
    "Scott Boland",
    "nathan ellis",
    "mitchell jhonson",
    "Andrew Tye",
    "Sean Abbott",
    "Nathan Lyon",
    "Ashton Agar",
    "Adam Zampa",
    "Mitchell Swepson",
    "Xavier Doherty",
    
    "Gurinder Sandhu",
    "Nathan Coulter-Nile",
    
),
'42':(
    "Alyssa Healy",
    "Beth Mooney",
    "Ellyse Perry",
    "Phoebe Litchfield",
    "Ashleigh Gardner",
    "Tahlia McGrath",
    "Kim Garth",
    "Grace Harris",
    "Annabel Sutherland",
    "Georgia Voll",
    "Georgia Wareham",
    "Alana King",
    "Sophie Molineux",
    "Megan Schutt",
    "Darcie Brown",
    "Heather Graham",
    "Nicole Faltum",
    "Tayla Vlaeminck",
    "Charli Knott",
    "Katie Mack",
    "Maddy Darke"
),
#ENGLAND-----------------------------------------------------------------------------------------------------------------------------------------------------

'13':(
    "Joe Root",
    "Alastair Cook",
    "Jonathan Trott",
    "Ian Bell",
    "Jonny Bairstow",
    "Ben Duckett",
    "Zak Crawley",
    "Rory Burns",
    "Haseeb Hameed",
    "Ollie Pope",
    "Harry Brook",
    "Jason Roy",
    "Alex Hales",
    "Dawid Malan",
    "Eoin Morgan",
    "Jos Buttler",
    "James Vince",
    "Keaton Jennings",
    "Gary Ballance",
    "Sam Billings",
    "Dom Sibley",
    "Liam Livingstone",
    "Moeen Ali",
    "Ben Stokes",
    "Rob Key"
),
'23':(
    "Ben Stokes",
    "Moeen Ali",
    "Chris Woakes",
    "Sam Curran",
    "Tom Curran",
    "David Willey",
    "Liam Livingstone",
    "Will Jacks",
    "Ben Duckett",
    "Joe Root",
    "Reece Topley",
    "Craig Overton",
    "Jamie Overton",
    "Luke Wright",
    "Adil Rashid",
    "Ravi Bopara",
    "Paul Collingwood",
    "James Franklin",
    "Daryl Mitchell",
    "George Garton",
    "Jordan Thompson",
    "Matt Critchley",
    "Brydon Carse",
    "Lewis Gregory",
    "Tim Bresnan"
),
'33':(
    "James Anderson",
    "Stuart Broad",
    "Jofra Archer",
    "Mark Wood",
    "Chris Woakes",
    "Ollie Robinson",
    "Reece Topley",
    "David Willey",
    "Adil Rashid",
    "Graeme Swann",
    "Monty Panesar",
    "Jack Leach",
    "Matthew Potts",
    "Saqib Mahmood",
    "Tymal Mills",
    "Steven Finn",
    "Jake Ball",
    "Chris Jordan",
    "Ben Stokes",
    "Craig Overton",
    "Jamie Overton",
    "Mark Davies",
    "James Tredwell",
    "Matthew Fisher",
    "Jade Dernbach"
),
'43':(
    "Heather Knight",
    "Nat Sciver-Brunt",
    "Sophie Ecclestone",
    "Sarah Glenn",
    "Amy Jones",
    "Danni Wyatt",
    "Sophia Dunkley",
    "Kate Cross",
    "Lauren Bell",
    "Charlie Dean",
    "Alice Capsey",
    "Freya Kemp",
    "Issy Wong",
    "Linsey Smith",
    "Emma Lamb",
    "Tammy Beaumont",
    "Bryony Smith",
    "Mady Villiers",
    "Bess Heath",
    "Georgia Elwiss",
    "Kirstie Gordon",
    "Alex Hartley",
    "Hollie Armitage",
    "Sarah Taylor",
    "Fran Wilson"
),
#NEW ZEALAND-----------------------------------------------------------------------------------------------------------------------------------------------------
'14':(
    "Kane Williamson",
    "Ross Taylor",
    "Tom Latham",
    "Martin Guptill",
    "Devon Conway",
    "Daryl Mitchell",
    "Henry Nicholls",
    "Finn Allen",
    "Will Young",
    "Colin Munro",
    "BJ Watling",
    "Dean Brownlie",
    "Tom Blundell",
    "Glenn Phillips",
    "Mark Chapman",
    "George Worker",
    "Hamish Rutherford",
    "Jeet Raval",
    "Luke Ronchi",
    "Jimmy Neesham",
    "Neil Broom",
    "Michael Bracewell",
    "Rachin Ravindra",
    "Rob Nicol",
    "Peter Fulton"
),
'24':(
    "Corey Anderson",
    "Jimmy Neesham",
    "Mitchell Santner",
    "Colin de Grandhomme",
    "Daryl Mitchell",
    "Rachin Ravindra",
    "Michael Bracewell",
    "Doug Bracewell",
    "Nathan McCullum",
    "Grant Elliott",
    "Scott Styris",
    "Glenn Phillips",
    "Mark Chapman",
    "Kyle Jamieson",
    "Ish Sodhi",
    "Todd Astle",
    "Anton Devcich",
    "Dean Brownlie",
    "Colin Munro",
    "Ajaz Patel",
    "Logan van Beek",
    "George Worker",
    "James Franklin",
    "Bruce Martin",
    "Jacob Duffy"
),
'34':(
    "Trent Boult",
    "Tim Southee",
    "Neil Wagner",
    "Matt Henry",
    "Kyle Jamieson",
    "Adam Milne",
    "Lockie Ferguson",
    "Mitchell McClenaghan",
    "Ish Sodhi",
    "Ajaz Patel",
    "Matt McEwan",
    "Doug Bracewell",
    "Hamish Bennett",
    "Ben Wheeler",
    "Seth Rance",
    "Jacob Duffy",
    "Jeetan Patel",
    "Todd Astle",
    "Blair Tickner",
    "Ed Nuttall",
    "Will O Rourke",
    "Scott Kuggeleijn",
    "Mark Gillespie",
    "Travis Muller",
    "Andy McKay"
),
'44':(
    "Sophie Devine",
    "Amelia Kerr",
    "Suzie Bates",
    "Jess Kerr",
    "Brooke Halliday",
    "Maddy Green",
    "Georgia Plimmer",
    "Bella James",
    "Izzy Gaze",
    "Polly Inglis",
    "Flora Devonshire",
    "Eden Carson",
    "Bree Illing",
    "Lea Tahuhu",
    "Rosemary Mair",
    "Hannah Rowe",
    "Emma McLeod",
    "Lauren Down",
    "Rebecca Burns"),
#SOUTH AFRICA-----------------------------------------------------------------------------------------------------------------------------------------------------
'15':(
    "AB de Villiers",
    "Hashim Amla",
    "Faf du Plessis",
    "Quinton de Kock",
    "Aiden Markram",
    "Temba Bavuma",
    "Rassie van der Dussen",
    "Dean Elgar",
    "Graeme Smith",
    "JP Duminy",
    "Heinrich Klaasen",
    "Reeza Hendricks",
    "David Miller",
    "Theunis de Bruyn",
    "Kyle Verreynne",
    "Sarel Erwee",
    "Keegan Petersen",
    "Tony de Zorzi",
    "Rilee Rossouw",
    "Colin Ingram",
    "Zubayr Hamza",
    "Richard Levi",
    "Stephen Cook",
    "Pieter Malan",
    "Stiaan van Zyl"
),
'25':(
    "Jacques Kallis",
    "Shaun Pollock",
    "JP Duminy",
    "Dwaine Pretorius",
    "Andile Phehlukwayo",
    "Chris Morris",
    "Albie Morkel",
    "David Wiese",
    "Wayne Parnell",
    "Vernon Philander",
    "Keshav Maharaj",
    "Wiaan Mulder",
    "Marco Jansen",
    "George Linde",
    "Farhaan Behardien",
    "Ryan McLaren",
    "Robin Peterson",
    "Rory Kleinveldt",
    "Justin Ontong",
    "Senuran Muthusamy",
    "Hardus Viljoen",
    "Daryn Dupavillon",
    "Malusi Siboto",
    "Simon Harmer",
    "Beuran Hendricks"
),
'35':(
    "Kagiso Rabada",
    "Dale Steyn",
    "Morne Morkel",
    "Lungi Ngidi",
    "Anrich Nortje",
    "Imran Tahir",
    "Tabraiz Shamsi",
    "Keshav Maharaj",
    "Vernon Philander",
    "Lonwabo Tsotsobe",
    "Wayne Parnell",
    "Beuran Hendricks",
    "Kyle Abbott",
    "Marchant de Lange",
    "Sisanda Magala",
    "Duane Olivier",
    "Rusty Theron",
    "Gerald Coetzee",
    "Tshwane Koto",
    "Ottniel Baartman",
    "Daryn Dupavillon",
    "Hardus Viljoen",
    "Junior Dala",
    "Glenton Stuurman",
),
'45':(
    "Laura Wolvaardt",
    "Tazmin Brits",
    "Anneke Bosch",
    "Nadine de Klerk",
    "Annerie Dercksen",
    "Marizanne Kapp",
    "Suné Luus",
    "Chloé Tryon",
    "Sinalo Jafta",
    "Karabo Meso",
    "Ayabonga Khaka",
    "Masabata Klaas",
    "Tumi Sekhukhune",
    "Nonkululeko Mlaba",
    "Nondumiso Shangase",
    "Ayanda Hlubi",
    "Miané Smit",
    "Lara Goodall",
    "Andrie Steyn",
    "Ashlyn Kilowan",
    "Anneke Bosch",
    "Kelly Smuts",
    "Alex Hartley",
    "Lea Tremaine"
),
#WEST INDIES-----------------------------------------------------------------------------------------------------------------------------------------------------
'16':(
    "Chris Gayle",
    "Shai Hope",
    "Shimron Hetmyer",
    "Nicholas Pooran",
    "Darren Bravo",
    "Kraigg Brathwaite",
    "Evin Lewis",
    "Lendl Simmons",
    "Marlon Samuels",
    "Kieron Powell",
    "Brandon King",
    "Rovman Powell",
    "Johnson Charles",
    "Dwayne Smith",
    "Andre Fletcher",
    "Devon Smith",
    "Sunil Ambris",
    "Kyle Hope",
    "Leon Johnson",
    "Jeremy Solozano",
    "Darren Sammy Jr.",
    "Shamarh Brooks",
    "Keacy Carty",
    "Tagenarine Chanderpaul",
    "Sherfane Rutherford"
),
'26':(
    "Jason Holder",
    "Andre Russell",
    "Kieron Pollard",
    "Dwayne Bravo",
    "Roston Chase",
    "Carlos Brathwaite",
    "Kyle Mayers",
    "Rahkeem Cornwall",
    "Fabian Allen",
    "Sunil Narine",
    "Akeal Hosein",
    "Raymon Reifer",
    "Jonathan Carter",
    "Jason Mohammed",
    "Kevin Sinclair",
    "Yannic Cariah",
    "Sherman Lewis",
    "Romario Shepherd",
    "Keemo Paul",
    "Justin Greaves",
    "Alick Athanaze",
    "Jomel Warrican",
    "Hayden Walsh Jr.",
    "Ashley Nurse",
    "Nikita Miller"
),
'36':(
    "Kemar Roach",
    "Shannon Gabriel",
    "Alzarri Joseph",
    "Oshane Thomas",
    "Sheldon Cottrell",
    "Obed McCoy",
    "Kesrick Williams",
    "Ravi Rampaul",
    "Fidel Edwards",
    "Jerome Taylor",
    "Shane Shillingford",
    "Devendra Bishoo",
    "Sulieman Benn",
    "Shamar Joseph",
    "Anderson Phillip",
    "Jayden Seales",
    "Miguel Cummins",
    "Delorn Johnson",
    "Jason Dawes",
    "Gavin Tonge",
    "Darren Sammy",
    "Tino Best",
    "Rayad Emrit",
    "Hayden Walsh Sr.",
    "Gudakesh Motie"
),
'46':(
    "Hayley Matthews",
    "Stafanie Taylor",
    "Shemaine Campbelle",
    "Chinelle Henry",
    "Shamilia Connell",
    "Aaliyah Alleyne",
    "Kycia Knight",
    "Kyshona Knight",
    "Chedean Nation",
    "Rashada Williams",
    "Zaida James",
    "Karishma Ramharack",
    "Shabika Gajnabi",
    "Qiana Joseph",
    "Jannillea Glasgow",
    "Cherry-Ann Fraser",
    "Kaysia Schultz",
    "Trishan Holder",
    "Djenaba Joseph",
    "Sheneta Grimmond",
    "Natasha McLean",
    "Reniece Boyce",
    "Britney Cooper",
    "Afy Fletcher",
    "Anisa Mohammed"
)
















    
    
    
    
    
    
    
    }

